runtime: java21
entrypoint: 'java -jar studyshare-all.jar'

handlers:
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
  - url: /static/*
    static_dir: static